[package]
name = "jogo-do-galo"
version = "0.1.0"
authors = ["joaompfe <joaofe2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
